CREATE SCHEMA IF NOT EXISTS `universidad` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `universidad` ;

CREATE TABLE IF NOT EXISTS `universidad`.`CARRERA` (
  `ID_CARRERA` INT NULL AUTO_INCREMENT COMMENT 'IDENTIFICADOR DE CARRERA, ACEPTA 0-9 ES PRIMARY KEY Y ES AUTOINCREMENTABLE',
  `NOMBRE_CARRERA` VARCHAR(45) NULL COMMENT 'NOMBRE QUE TIENE LA CARRERA, ACEPTA DE A-Z',
  `EDIFICIO` VARCHAR(45) NULL COMMENT 'EDIFICIO DONDE PERTENECE LA CARRERA  ACEPTA VALORES A-Z ',
  `JEFE_CARRERA` VARCHAR(45) NULL COMMENT 'JEFE ENCARGADO DE LA CARRERA, ACEPTA VALORES DE A-Z',
  `LABORATORIO` VARCHAR(45) NULL COMMENT 'LABORATORIOS QUE TIENE ACCESO LA CARRERA ACEPTA VALORES DE A-Z',
  `ACTIVO_CARRERA` TINYINT(1) NULL COMMENT 'TIPO DE DATO BOOLEAN, ESPECIFICA SI LA CARRERA ESTA ACTIVA',
  `FECHA_REGISTRO` TIMESTAMP NULL COMMENT 'FECHA DE REGISTRO DE LOS DATOS ES DE TIPO TIMESTAMP',
  `USUARIO_REGISTRO` VARCHAR(45) NULL COMMENT 'USUARIO QUE REALIZO LOS REGISTROS ACEPTA VALORES DE A-Z',
  `FECHA_ACTUALIZACION` TIMESTAMP NULL COMMENT 'FECHA EN QUE SE REALIZA UNA ACTUALIZACION A LA BASE, ES DE TIPO TIMESTAMP',
  `USUARIO_ACTUALIZACION` VARCHAR(45) NULL COMMENT 'USUARIO QUE REALIZO LA ULTIMA ACTUALIZACION, ACEPTA VALORES DE A-Z',
  PRIMARY KEY (`ID_CARRERA`) )
ENGINE = InnoDB;



CREATE TABLE IF NOT EXISTS `universidad`.`ALUMNO` (
  `ID_ALUMNO` INT NULL AUTO_INCREMENT COMMENT 'IDENTIFICADOR DE ALUMNO ES PRIMARY KEY Y ES AUTOINCREMENTABLE',
  `NOMBRE` VARCHAR(45) NULL COMMENT 'NOMBRE DEL ALUMNO,ACEPTA DE A-Z',
  `APELLIDO_PATERNO` VARCHAR(45) NULL COMMENT 'APELLIDO PATERNO DEL ALUMNO, ACEPTA VALORES DE A-Z',
  `APELLIDO_MATERNO` VARCHAR(45) NULL COMMENT 'APELLIDO MATERNO DEL ALUMNO, ACEPTA VALORES DE A-Z',
  `TELEFONO` INT NULL COMMENT 'TELEFONO DEL ALUMNO, ACEPTA VALORES DE 0-9',
  `EDAD` INT NULL COMMENT 'EDAD DEL ALUMNO, ACEPTA VALORES DE 0-9',
  `ID_CARRERA` INT NULL COMMENT 'IDENTIFICADOR DE CARRERA A LA QUE PERTENECE EL ALUMNO, ES FOREIGN KEY, SE RELACIONA CON LA TABLA CARRERA, ACEPTA VALORES DE 0-9',
  `ACTIVO_ALUMNO` TINYINT(1) NULL COMMENT 'ESPECIFICA SI EL ALUMNO ESTA ACTIVO ES DE TIPO BOOLEAN',
  `FECHA_REGISTRO` TIMESTAMP NULL COMMENT 'FECHA DEL REGISTRO, ES DE TIPO TIMESTAMP',
  `USUARIO_REGISTRO` VARCHAR(45) NULL COMMENT 'USUARIO QUE REALIZO EL REGISTRO ACEPTA DE A-Z',
  `FECHA_ACTUALIZACION` TIMESTAMP NULL COMMENT 'FECHA DE LA ULTIMA ACTUALIZACION ES DE TIPO TIMESTAMP',
  `USUARIO_ACTUALIZACION` VARCHAR(45) NULL COMMENT 'USUARIO QUE REALIZO LA ACTUALIZACION, ACEPTA DE A-Z',
  PRIMARY KEY (`ID_ALUMNO`),
    FOREIGN KEY (`ID_CARRERA`) REFERENCES CARRERA(`ID_CARRERA`))
	ENGINE=InnoDB;
    


