INSERT INTO CARRERA VALUES (NULL,'Ingernieria Sistemas','E','Armando Aguayo','E2',TRUE,NULL,NULL,NULL,NULL);
INSERT INTO CARRERA VALUES (NULL,'Ingernieria Mecatronica','D','Alejandro Ramirez','D2',TRUE,NULL,NULL,NULL,NULL);
INSERT INTO CARRERA VALUES (NULL,'Ingernieria Civil','B','Arturo Flores','B1',TRUE,NULL,NULL,NULL,NULL);
INSERT INTO CARRERA VALUES (NULL,'Ingernieria Industrial','B','Luis Martinez','B3',TRUE,NULL,NULL,NULL,NULL);
INSERT INTO CARRERA VALUES (NULL,'Ingernieria Electromecanica','A','Hernan Lopez','A1',False,NULL,NULL,NULL,NULL);



INSERT INTO ALUMNO VALUES (NULL,'Rodrigo','Topete','Velazquez',58793181,22,001,TRUE,NULL,NULL,NULL,NULL);
INSERT INTO ALUMNO VALUES (NULL,'Andres','Ramos','Rios',56789578,22,001,TRUE,NULL,NULL,NULL,NULL);
INSERT INTO ALUMNO VALUES (NULL,'Luis','Moctezuma','Martinez',56238965,24,002,TRUE,NULL,NULL,NULL,NULL);
INSERT INTO ALUMNO VALUES (NULL,'Jesus','Gutierrez','Rodriguez',56782345,21,003,TRUE,NULL,NULL,NULL,NULL);
INSERT INTO ALUMNO VALUES (NULL,'Cesar','Mora','Duarte',54678935,24,001,FALSE,NULL,NULL,NULL,NULL);

